git config --global alias.alias 'config --global --get-regexp ^alias\.'
git config --global alias.abort 'reset --hard HEAD'
git config --global alias.br 'branch'
git config --global alias.ci 'commit'
git config --global alias.co 'checkout'
git config --global alias.fancy 'fancy = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan)<%an>%Creset' --abbrev-commit --date=relative'
git config --global alias.last 'log -1 HEAD'
git config --global alias.ls 'branch -av'
git config --global alias.oops 'reset --soft HEAD~1'
git config --global alias.pop 'stash pop --index'
git config --global alias.save 'stash save'
git config --global alias.st 'status'
git config --global alias.undo 'reset --hard'
git config --global alias.unstage 'reset'