#!/bin/sh

applications=(
    'alfred'
    'atom'
    'bettertouchtool'
    'dash'
    'dropbox'
    'firefox'
    'flux'
    'github'
    'google-chrome'
    'google-drive'
    'iterm2'
    'mou'
    'mysqlworkbench'
    'sequel-pro'
    'sourcetree'
    'slack'
    'spotify'
)

brew tap caskroom/cask

for app in "${applications[@]}"
do
    echo "\n\n"
    echo "Installing $app..."
    brew cask install $app
done
