#!/bin/sh

modules=(
    'bower'
    'grunt'
    'grunt-autoprefixer'
    'grunt-bower-install'
    'grunt-cli'
    'grunt-contrib-clean'
    'grunt-contrub-concat'
    'grunt-contrib-sass'
    'grunt-contrib-uglify'
    'grunt-contrib-watch'
    'grunt-grunticon'
    'grunt-imageoptim'
    'grunt-sass'
    'grunt-shell'
    'grunt-svgstore'
    'imageoptim-cli'
    'load-grunt-tasks'
    'node-sass'
    'markdown'
)

echo "\nInstalling Node modules via npm..."
for module in "${modules[@]}"
do
    if [ ! -h /usr/local/bin/$module  ]
    then
        echo "\n\n"
        echo "Installing $module..."
        npm install -g $module
    else
        echo "\n\n"
        echo "$module is already installed, skipping ahead..."
    fi
done
