#!/bin/sh

echo "\nDotfile Uninstallation\n----------------------"

# Remove Fonts
echo "Uninstalling fonts..."
rm -rf $HOME/.fonts/SourceCodePro $HOME/.fonts/powerline-fonts

# Uninstall pip packages
echo "Uninstalling pip packages..."
pip uninstall -r $HOME/dotfiles/requirements.txt

# Uninstall brew formulae
while true; do
    read -p "Do you want to uninstall the brew packages? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Uninstalling brew formulae. NOTE: spawned formulae dependencies may remain..."
                brew update
                brew doctor
                brew uninstall git --force
                brew uninstall node --force
                brew uninstall mysql --force
                brew uninstall packer --force
                brew uninstall pyenv --force
                brew uninstall pyenv-virtualenvwrapper --force
                brew uninstall vim --force
                break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.\n";;
    esac
done

# Restore .zshrc
echo "Restoring zsh setup..."
rm $HOME/.zshrc
cp $HOME/dotfiles/dotfile_backups/.zshrc_backup $HOME/.zshrc

# Restore .vimrc
echo "Restoring vim setup..."
rm $HOME/.vimrc
cp $HOME/dotfiles/dotfile_backups/.vimrc_backup $HOME/.vimrc

# Restore git settings
echo "Restoring git setup..."
rm $HOME/.gitconfig
cp $HOME/dotfiles/dotfile_backups/.gitconfig_backup $HOME/.gitconfig

if [ -h "/usr/local/bin/git_find_replace_author" ]
then
    rm /usr/local/bin/git_find_replace_author
fi

# Remove dotfiles repository
echo
while true; do
    read -p "Would you like to remove the dotfiles repository? [y/n]" yn
    case $yn in
        [Yy]* ) echo "You successfully uninstalled the dotfiles."
                break;;
        [Nn]* ) echo "You successfully uninstalled the dotfiles, but the repository still exists."
                exit;;
        * ) echo "Please answer yes or no.\n";;
    esac
done
cd $HOME
source ~/.zshrc
rm -rf $HOME/dotfiles