#!/bin/sh

# temporarily disabled
exit;;

    echo "                      _                           "
    echo "  _ __ __ _ _ __   __| |  ___  ___  __ _ _   _    "
    echo " | '__/ _' | '_ \ / _' | / __|/ _ \/ _' | | | |   "
    echo " | | | (_| | | | | (_| | \__ \  __/ (_| | |_| |   "
    echo " |_|  \__,_|_| |_|\__,_| |___/\___|\__,_|\__, |   "
    echo "                                         |___/    "
    echo "\nYou pulled down the dotfiles repository!\n----------------------------------------"

while true
do
    read -p "Would you like to run through the setup right now? [y/n] " yn
    case $yn in
        [Yy]* ) MYLOC=$(dirname -- $0)
                source $MYLOC/../../setup
                break;;
        [Nn]* ) while true; do
                    echo "\nThe current git user is $(git config --global user.name) <$(git config --global user.email)>."
                    read -p "Do you wish specify the git user right now? [y/n] " yn
                    case $yn in
                        [Yy]* ) echo
                                read -p "What is the git user name? [First Last] " name
                                git config --global user.name "$name"
                                echo
                                read -p "What is the git user email? " email
                                git config --global user.email "$email"
                                break;;
                        [Nn]* ) exit;;
                        * ) echo "Please answer yes or no.\n";;
                    esac
                done
                exit;;
        * ) echo "Please answer yes or no.\n";;
    esac
done
